-- Matrimony Portal Seed Data
-- MySQL 8.0+ compatible
-- This file contains ONLY test/dummy data for development
-- Run this AFTER 01-schema.sql

USE matrimony_portal;

-- ===========================================
-- SAMPLE DATA INSERTION
-- ===========================================

-- Insert sample users
-- Note: Passwords are hashed with BCrypt. Default password for all: "password123"
-- BCrypt hash generated by Spring BCryptPasswordEncoder (strength 10)
-- status = ACTIVE so login works (User entity / AuthServiceImpl use status, not is_active)
INSERT INTO users (email, password, first_name, last_name, phone, role, status) VALUES
('rahul.sharma@example.com', '$2a$10$GXrtJ5LB1pJ5CVtH7oPVguk2QqtcQ6AqVdEH2IhzG8UOJW02HVHVG', 'Rahul', 'Sharma', '+919876543210', 'ADMIN', 'ACTIVE'),
('priya.verma@example.com', '$2a$10$GXrtJ5LB1pJ5CVtH7oPVguk2QqtcQ6AqVdEH2IhzG8UOJW02HVHVG', 'Priya', 'Verma', '+919876543211', 'EVENT_ORGANIZER', 'ACTIVE'),
('john.doe@example.com', '$2a$10$GXrtJ5LB1pJ5CVtH7oPVguk2QqtcQ6AqVdEH2IhzG8UOJW02HVHVG', 'John', 'Doe', '+919876543212', 'USER', 'ACTIVE'),
('jane.smith@example.com', '$2a$10$GXrtJ5LB1pJ5CVtH7oPVguk2QqtcQ6AqVdEH2IhzG8UOJW02HVHVG', 'Jane', 'Smith', '+919876543213', 'USER', 'ACTIVE'),
('alice.johnson@example.com', '$2a$10$GXrtJ5LB1pJ5CVtH7oPVguk2QqtcQ6AqVdEH2IhzG8UOJW02HVHVG', 'Alice', 'Johnson', '+919876543214', 'USER', 'ACTIVE');

-- Insert sample subscription plans
INSERT INTO subscription_plans (plan_name, plan_type, price_monthly, price_yearly, max_profiles_view, max_messages, max_photos, priority_matching, advanced_filters, customer_support) VALUES
('Free Plan', 'FREE', 0.00, 0.00, 10, 5, 3, false, false, 'NONE'),
('Premium Plan', 'PREMIUM', 999.00, 9999.00, 100, 50, 10, true, true, 'PHONE'),
('VIP Plan', 'VIP', 1999.00, 19999.00, -1, -1, -1, true, true, 'PRIORITY');

-- Insert sample subscriptions
INSERT INTO subscriptions (user_id, plan_id, billing_cycle, start_date, is_active) VALUES
(3, 1, 'MONTHLY', CURDATE(), true),
(4, 2, 'MONTHLY', CURDATE(), true),
(5, 3, 'YEARLY', CURDATE(), true);

-- Insert sample profiles (users 2=organizer, 3–5=regular users)
-- Organizer (2) needs a profile so GET/PUT organizer profile and Edit Profile work (city, state, about_me).
INSERT INTO profiles (user_id, date_of_birth, gender, religion, caste, occupation, education, city, state, about_me, preferences) VALUES
(2, '1988-03-22', 'FEMALE', NULL, NULL, 'Event Organizer', NULL, 'Mumbai', 'Maharashtra', 'I organise matrimonial events and help singles connect. Welcome to our meetups!', NULL),
(3, '1990-05-15', 'MALE', 'Hindu', 'Brahmin', 'Software Engineer', 'Bachelor of Technology', 'Mumbai', 'Maharashtra', 'I am a software engineer looking for a life partner who shares similar values.', 'Looking for a caring and understanding partner.'),
(4, '1992-08-20', 'FEMALE', 'Hindu', 'Kayastha', 'Teacher', 'Master of Arts', 'Delhi', 'Delhi', 'I am a teacher passionate about education and family values.', 'Seeking a supportive partner who values family and education.'),
(5, '1988-12-10', 'MALE', 'Christian', 'Catholic', 'Doctor', 'Doctor of Medicine', 'Chennai', 'Tamil Nadu', 'I am a doctor dedicated to helping others and building a loving family.', 'Looking for a compassionate partner who shares my commitment to service.');

-- Insert sample events
INSERT INTO events (organizer_id, title, description, event_date, venue, city, state, max_participants, registration_fee, status) VALUES
(2, 'Matrimony Meetup 2024', 'A grand matrimonial event bringing together eligible singles from across the city.', '2024-12-15 18:00:00', 'Grand Ballroom, Taj Hotel', 'Mumbai', 'Maharashtra', 200, 500.00, 'UPCOMING'),
(2, 'Speed Dating Event', 'Fast-paced speed dating event for busy professionals.', '2024-11-20 19:00:00', 'Lounge Bar, ITC Grand', 'Delhi', 'Delhi', 50, 1000.00, 'UPCOMING');

-- Insert sample messages
INSERT INTO messages (sender_id, receiver_id, subject, content) VALUES
(3, 4, 'Hello from John', 'Hi Jane, I came across your profile and would like to know more about you.'),
(4, 3, 'Re: Hello from John', 'Hello John, thank you for reaching out. I am interested in learning more about you as well.');

-- Insert sample user interests
INSERT INTO user_interests (from_user_id, to_user_id, interest_type, compatibility_score, notes) VALUES
(3, 4, 'LIKE', 85.5, 'Great compatibility match based on shared interests.'),
(4, 3, 'SHORTLIST', 88.0, 'Very promising candidate for further interaction.');

-- Insert sample event registrations
INSERT INTO event_registrations (user_id, event_id, payment_status) VALUES
(3, 1, 'PAID'),
(4, 1, 'PENDING'),
(5, 2, 'PAID');

-- Insert sample payments
INSERT INTO payments (user_id, payment_type, amount, payment_method, transaction_id, status) VALUES
(3, 'SUBSCRIPTION', 999.00, 'Credit Card', 'TXN_001', 'COMPLETED'),
(4, 'EVENT_REGISTRATION', 500.00, 'UPI', 'TXN_002', 'COMPLETED'),
(5, 'SUBSCRIPTION', 1999.00, 'Net Banking', 'TXN_003', 'COMPLETED');

-- Insert sample notifications
INSERT INTO notifications (user_id, notification_type, title, message, action_url) VALUES
(3, 'NEW_MATCH', 'New Match Found!', 'You have a new potential match. Check it out!', '/matches'),
(4, 'NEW_MESSAGE', 'New Message Received', 'You have received a new message from John.', '/messages');

-- Insert sample notification preferences
INSERT INTO notification_preferences (user_id, email_notifications, push_notifications, sms_notifications, new_matches, new_messages, event_updates) VALUES
(3, true, true, false, true, true, true),
(4, true, true, true, true, true, false),
(5, false, true, false, true, false, true);
